import tkinter as tk
window=tk.Tk()
window.geometry("240x140")
window.title("Calculator")
entry=tk.Entry(window,font=("helitica",15))
button1=tk.Button(window,text="C",font=("helitica",23),height=1,width=4,fg="steel blue")
button2=tk.Button(window,text="()",font=("helitica",23),height=1,width=4,fg="steel blue")
button3=tk.Button(window,text="%",font=("helitica",23),height=1,width=4,fg="steel blue")
button4=tk.Button(window,text="/",font=("helitica",23),height=1,width=4,fg="steel blue")
button5=tk.Button(window,text="7",font=("helitica",23),height=1,width=4,fg="black")
button6=tk.Button(window,text="8",font=("helitica",23),height=1,width=4,fg="black")
button7=tk.Button(window,text="9",font=("helitica",23),height=1,width=4,fg="black")
button8=tk.Button(window,text="x",font=("helitica",23),height=1,width=4,fg="steel blue")
button9=tk.Button(window,text="4",font=("helitica",23),height=1,width=4,fg="black")
button10=tk.Button(window,text="5",font=("helitica",23),height=1,width=4,fg="black")
button11=tk.Button(window,text="6",font=("helitica",23),height=1,width=4,fg="black")
button12=tk.Button(window,text="-",font=("helitica",23),height=1,width=4,fg="steel blue")
button13=tk.Button(window,text="1",font=("helitica",23),height=1,width=4,fg="black")
button14=tk.Button(window,text="2",font=("helitica",23),height=1,width=4,fg="black")
button15=tk.Button(window,text="3",font=("helitica",23),height=1,width=4,fg="black")
button16=tk.Button(window,text="+",font=("helitica",23),height=1,width=4,fg="steel blue")
button17=tk.Button(window,text="00",font=("helitica",23),height=1,width=4,fg="black")
button18=tk.Button(window,text="0",font=("helitica",23),height=1,width=4,fg="black")
button19=tk.Button(window,text=".",font=("helitica",23),height=1,width=4,fg="black")
button20=tk.Button(window,text="=",font=("helitica",23),height=1,width=4,bg="lime green",fg="white")




entry.grid(column=0,row=0,columnspan=5,rowspan=2,ipady=30,ipadx=52)
button1.grid(column=0,row=2)
button2.grid(column=1,row=2)
button3.grid(column=2,row=2)
button4.grid(column=3,row=2)
button5.grid(column=0,row=3)
button6.grid(column=1,row=3)
button7.grid(column=2,row=3)
button8.grid(column=3,row=3)
button9.grid(column=0,row=4)
button10.grid(column=1,row=4)
button11.grid(column=2,row=4)
button12.grid(column=3,row=4)
button13.grid(column=0,row=5)
button14.grid(column=1,row=5)
button15.grid(column=2,row=5)
button16.grid(column=3,row=5)
button17.grid(column=0,row=6)
button18.grid(column=1,row=6)
button19.grid(column=2,row=6)
button20.grid(column=3,row=6)
window.mainloop()


